### ISSUE TITLE
Unable to sign in to Google

### ISSUE THREAD

**Issue by mistyron** [flathub/io.github.liberodark.OpenDrive#11]
The error message I'm getting:
Authorization Error
Error 401: disabled_client
Sign in with Google temporarily disabled for this app. This app has not been verified yet by Google in order to use Google Sign In.

**Comment by x80486** [comment]
@mistyron, this is not a problem with the Flatpak, but the application itself.

It looks to me that this application is pretty much dead by now. There are plenty of issues around this (and many other stuff) in the [application's repository](https://github.com/liberodark/ODrive/). I would recommend to use `VGrive` — which is also stale, but it works for the most part.
