### ISSUE TITLE
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

### ISSUE THREAD

**Issue by Zorono** [flathub/io.github.liberodark.OpenDrive#12]
Info: org.freedesktop.Platform.VAAPI.Intel//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: org.freedesktop.Platform.GL.default//20.08 is end-of-life, with reason:
   org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.

**Comment by x80486** [comment]
[OpenDrive](https://github.com/liberodark/ODrive) itself seems to be abandoned. I'm just waiting on the official notice from the developer(s) to retire it from `Flathub`.
