### ISSUE TITLE
Cannot connect to my Google Drive Account

### ISSUE THREAD

**Issue by amichae1** [flathub/io.github.liberodark.OpenDrive#8]
When I try to connect to my google account via the OpenDrive App, I get the error:

Google couldn't sign you in
This browser or app may not be secure. Learn More..

I can log in via Chrome but I would like to be able to use the app.
I am new to Endless OS and Linux in general so I am a little stuck.
Any ideas ?
Thanks Andreas

**Comment by x80486** [comment]
I don't think this is related only with the Flatpak artifact, have a look at [this issue](https://github.com/liberodark/ODrive/issues/147/).

I would recommend you to stop by that repo and chime in, if necessary.

**Comment by amichae1** [comment]
Thanks for the reply. I don't really know what any of that means but I will take a look for sure :)

**Comment by x80486** [comment]
@amichae1, I'm going to close this one for now. Feel free to open it up again if you think it's a Flatpak issue.

I would recommend you to take a look at **VGrive** as an alternative since **ODrive** haven't had any updates so far for almost two years.
